//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApicrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stud_Details
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
